name: 'Terraform'

on:
  push:
    paths-ignore: 
    - 'README.*'
    - 'img/**'
    - 'ansible'
    branches:
    - master
  pull_request:
    paths-ignore: 
    - 'README.*'
    - 'img/**'
    - 'ansible'
    branches: [ master ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: [0.12.7, 0.12.20, 0.12.28]

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # A specific version of Terraform CLI can be installed
    - name: Setup Terraform ${{ matrix.terraform_version }}
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ matrix.terraform_version }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check -recursive

    # Generates an execution plan for Terraform
    - name: Terraform Validate
      run: terraform validate


